# Site settings
title: Brendan Regnery
email: bjregnery(at)ucdavis.edu
description: >
  The personal website of Brendan Regnery.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://bregnery.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/bregnery/bregnery.github.io
git_edit_address: https://github.com/bregnery/bregnery.github.io/tree/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: Darkly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _cv
    type: cv
  values:
    layout: cv
    sectionid: cv
    seo:
      type: "WebPage"

- scope:
    path: _ecology
    type: ecology
  values:
    layout: ecology
    sectionid: ecology
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  cv:
    permalink: /:collection/:path/
    output: true
  ecology:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
